### ISSUE TITLE
Code description/usage

### ISSUE THREAD

**Issue by matanox** [CoNLL-UD-2018/UDPipe-Future#1]
Is this kind of a next-gen rewrite of UDPipe, or something else?

**Comment by foxik** [comment]
This is a prototype for UDPipe 2.0. The prototype consists of tagging and parsing and is purely in Python. It participated in CoNLL 2018 UD Shared Task and was one of three winners.

The UDPipe 2.0, based on this prototype, will be again C++ application (with the same API as now), and we target to release it with UD 2.3, i.e., 15 Nov 2018.

I am adding this information to the README now.

**Comment by matanox** [comment]
@foxik thanks! does it also do morphological disambiguation?

**Comment by foxik** [comment]
@matanster  What exactly do you mean by that? the FEATS column? Anyway, the prototype expects to get tokenized and segmented input, and fills UPOS, XPOS, FEATS, LEMMA, HEAD and DEPREL columns in the CoNLL-U format.
