### ISSUE TITLE
ELMo files format

### ISSUE THREAD

**Issue by pjox** [CoNLL-UD-2018/UDPipe-Future#15]
Hello,

Could you give me some insight on the ELMo file format? 

If I understand correctly I have to generate 3 ELMo files (one for train, one for dev and one for test), where the first column is the token and the subsequent columns are the embeddings, then I can use `/embeddings/sources/convert.py` to convert the 3 files to `.npz` and these I can use with the parser. Is that correct ? Would this work with other contextualized word embeddings like BERT?

Thank you in advance for your help.

**Comment by foxik** [comment]
I added the scripts for generating BERT embeddings to `embeddings/bert` (while renaming the original `embeddings/sources` to `embeddings/vec_to_npz`).

The ELMo-like files (generally any contextualized embeddings) are a `.npz` files, containing an array of `numpy` tensors, each tensor representing embeddings of a single sentence. Therefore, the `.npz` file should contain as many elements as there are sentences in the corresponding dataset, and each element should be of shape `[num_words_in_a_sentence, contextualized_embeddings_dimension]`.

The `vec_to_npz` does not help with ELMo-like embeddings, it only converts `word2vec`-like embeddings.

Closing, but feel free to ask additional questions.

**Comment by pjox** [comment]
Thank you so much for your quick reply! And for adding the BERT embeddings code!

Stupid (or lazy) question: what do you use to generate the `.npz` ELMo files then? Most of the libraries I know dump the embeddings of a text file in a `.hdf5` format

**Comment by foxik** [comment]
We used our own code, generated the embeddings using Flair and then saved them with `np.savez`. I do not have the code around, it was done by a co-author -- that is why I added only the BERT code.

**Comment by pjox** [comment]
Ok, no problem, I'll code something using the flair code base, thank you so much!

Just one more question, could you give me an example of the command to run the parser for a particular treebank, the danish treebank for example, using fastText embeddings and a custom Danish ELMo?

Thank you in advance once again!

**Comment by jowagner** [comment]
I wrote an elmo hdf5 to npz converter that supports both the output of `allennlp elmo` and the [elmoformanylangs](https://github.com/HIT-SCIR/ELMoForManyLangs) format, the latter requiring also the `.conllu` file to reconstruct the sentence order. It's not ready for public release but you can DM me for a copy for research purposes.
