### ISSUE TITLE
Raw text parse

### ISSUE THREAD

**Issue by interlark** [CoNLL-UD-2018/UDPipe-Future#17]
How can I perform multilingual parsing from **raw text** to **universal dependencies** with trained model?

**Comment by foxik** [comment]
This prototype takes segmented and tokenized text as input; in the shared task, I used the segmenter and tokenizer from the regular [UDPipe](https://ufal.mff.cuni.cz/udpipe).

**Comment by interlark** [comment]
Oh, now I see. Thank you.

**Comment by jowagner** [comment]
@interlark Note that the tokeniser of UDPipe is trained on UD treebank data and for some target languages this data is missing features frequently found in real world data, e.g. the Irish treebank contains no double quotes, resulting in tokens like `sliocht."` (CoNLL'17 wikipedia data).
