### ISSUE TITLE
Running trained models

### ISSUE THREAD

**Issue by danielhers** [CoNLL-UD-2018/UDPipe-Future#2]
Thank you for your code. I was playing around with it and managed to train a model. Do you also have a script to run a trained model on dev/test data?
I realize this is a prototype and is not supposed to be used in production, but I'd like to experiment with it if possible.
Thanks!

**Comment by foxik** [comment]
Sorry, I forgot about it. The exact same version as used in the ST is now in branch shared-task, and the master branch will be getting some post-ST improvements and experiments.

**Comment by danielhers** [comment]
Great, thanks!
