### ISSUE TITLE
Questions regarding the list of training and dev treebanks in the shared task

### ISSUE THREAD

**Issue by Chung-I** [CoNLL-UD-2018/UDPipe-Future#20]
Dear authors of UDPipe-Future,

Thank you all for releasing the source code used in the shared task.

I have a few questions however regarding the list of training treebanks used in the competition.

I'm working on a paper and would like to compare my proposed approach against participants from the CoNLL 2018 shared task.

However I couldn't find the original training data. The [training data](http://ufal.mff.cuni.cz/~zeman/soubory/release-2.2-st-train-dev-data.zip) seemed to be removed.
I found that there's a language list [here](https://github.com/CoNLL-UD-2018/UDPipe-Future/blob/master/langs) in the repo.

Is this the training and development set specified in the shared task? (7 treebanks in `langs` seemed to have no dev.conllu though, which is consistent with the description in the [task description](https://universaldependencies.org/conll18/proceedings/pdf/K18-2001.pdf))

Thank you so much!

**Comment by foxik** [comment]
As written on https://universaldependencies.org/conll18/data.html, the full package including the training data is now at http://hdl.handle.net/11234/1-2837 (however the archive includes also additional treebanks not present in the shared task). The http://hdl.handle.net/11234/1-2899 contains all test inputs (including baseline preprocessing).

To get the list of the original training data, you cannot use the list you mention (it is not from the `shared_task` branch). The list of treebanks which contained nonzero amount of training data is for example at https://github.com/CoNLL-UD-2018/UDPipe-Future/blob/shared-task/ud-2.2-conll18/iso_names.txt

@dan-zeman Dan, is the information about which UD 2.2 treebanks were part of the shared task available somewhere official?

**Comment by Chung-I** [comment]
Thank you! Appreciate the quick response.

So there were 73 treebanks (+1 mixed treebank in `iso_names.txt`) in the shared task, and the 61 development treebanks are exactly the `*-dev.conllu`s in those 73 treebanks in  https://github.com/CoNLL-UD-2018/UDPipe-Future/blob/shared-task/ud-2.2-conll18/iso_names.txt.

**Comment by dan-zeman** [comment]
> is the information about which UD 2.2 treebanks were part of the shared task available somewhere official?

I suppose that Table 1 on page 3 of the [shared task overview paper](https://universaldependencies.org/conll18/proceedings/pdf/K18-2001.pdf#page=3) is as official as it gets. Alternatively, you can consult one of the [per treebank result pages](https://universaldependencies.org/conll18/results-las.html). There are 82 treebanks with identifiers. Some of them do not have training data, so there will be fewer models than that.

**Comment by foxik** [comment]
Thanks Dan!
