### ISSUE TITLE
feature: option to set numpy seed

### ISSUE THREAD

**Issue by jowagner** [CoNLL-UD-2018/UDPipe-Future#7]
The option `--seed` does not set the numpy seed, which always remains 42 and determines how the training data is shuffled in each epoch. To not disturb reproduction of results, let's not change the behaviour of `--seed` but add a new option `--permutation-seed`.

**Comment by foxik** [comment]
I already did that in an internal version, and used the `--seed` (this is just a research prototype, so perfect replicability is not a goal; the GPU training is non-deterministic anyway).
